Optimizer:

  SGD:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0001

Scheduler:
  multistep:
    milestones: !!python/list [0.5, 0.75]
    gamma: 0.1
  cyclic:
    base_lr: 0.001
    max_lr: 0.2

NAT:
  dynamic:
    start_rate: 0.5
    end_epoch: 8
  static:
    start_rate: 0.75
    end_epoch: 60
